version: '3.7'
services:
  localstack:
    image: localstack/localstack:0.11.1
    ports:
      - "4567-4584:4567-4584"
      - "${LS_PORT_WEB_UI-8080}:${LS_PORT_WEB_UI-8080}"

    environment:
      - SERVICES=${LS_SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=${LS_PORT_WEB_UI- }
      - DOCKER_HOST=unix:///var/run/docker.sock

    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
       
  # container for portainer
  #    entrypoint: http://localhost:9000
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - "1111:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  
volumes:
  nginx-data:
  portainer_data: 
